---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-es-cert
spec:
  isCA: false
  dnsNames:
    - elasticsearch-es-http
    - elasticsearch-es-http.default.svc
    - elasticsearch-es-http.default.svc.cluster.local
    - elaticsearch.k8s.wafflelab.online
    - elaticsearch.k8s.wafflelab.net
    - elaticsearch.wafflelab.net
  subject:
    organizations:
      - wafflelab
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    kind: ClusterIssuer
    name: wafflelab-ca
  secretName: elasticsearch-es-cert
  usages:
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-kb-cert
spec:
  isCA: false
  dnsNames:
    - kibana-kb-http
    - kibana-kb-http.default.svc
    - kibana-kb-http.default.svc.cluster.local
    - kibana.k8s.wafflelab.online
    - kibana.k8s.wafflelab.net
    - kibana.wafflelab.net
  subject:
    organizations:
      - wafflelab
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    kind: ClusterIssuer
    name: wafflelab-ca
  secretName: kibana-kb-cert
  usages:
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fleet-cert
spec:
  isCA: false
  dnsNames:
    - fleet-http
    - fleet-http.default.svc
    - fleet-http.default.svc.cluster.local
    - fleet-server-agent-http.default.svc
    - fleet-server-agent-http
    - fleet.k8s.wafflelab.online
    - fleet.k8s.wafflelab.net
    - fleet.wafflelab.net
  subject:
    organizations:
      - wafflelab
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    kind: ClusterIssuer
    name: wafflelab-ca
  secretName: fleet-cert
  usages:
    - server auth
    - client auth
