---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-k8s
  namespace: default
spec:
  secretName: elasticsearch-es-secret
  isCA: false
  commonName: elasticsearch.k8s.wafflelab.online
  subject:
    organizations:
      - wafflelab
    organizationalUnits:
      - k8s
  dnsNames:
    - elasticsearch.k8s.wafflelab.online
    - elasticsearch.wafflelab.net
    - elasticsearch.k8s.wafflelab.net
    - elasticsearch-es-http
    - elasticsearch-es-http.default.svc
    - elasticsearch-es-http.default.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: wafflelab-net-ca
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 8760h
  renewBefore: 7200h
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-kb
spec:
  isCA: false
  dnsNames:
    - kibana-kb-http
    - kibana-kb-http.default.svc
    - kibana-kb-http.default.svc.cluster.local
    - kibana.k8s.wafflelab.online
    - kibana.k8s.wafflelab.net
    - kibana.wafflelab.net
  subject:
    organizations:
      - wafflelab
    organizationalUnits:
      - k8s
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    kind: ClusterIssuer
    name: wafflelab-net-ca
  secretName: kibana-kb-secret
  usages:
    - server auth
    - client auth
  duration: 8760h
  renewBefore: 7200h
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fleet
spec:
  isCA: false
  dnsNames:
    - fleet-http
    - fleet-http.default.svc
    - fleet-http.default.svc.cluster.local
    - fleet-server-agent-http.default.svc
    - fleet-server-agent-http
    - fleet.k8s.wafflelab.online
    - fleet.k8s.wafflelab.net
    - fleet.wafflelab.net
  subject:
    organizations:
      - wafflelab
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    kind: ClusterIssuer
    name: wafflelab-net-ca
  secretName: fleet-secret
  usages:
    - server auth
    - client auth
  duration: 8760h
  renewBefore: 7200h
