---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 9.1.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  secureSettings:
  - secretName: kibana-secret-settings
  http:
    service:
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.8.81
    tls:
      selfSignedCertificate:
        subjectAltNames:
          - ip: 192.168.8.81
          - dns: kibana.k8s.wafflelab.online
  podTemplate:
    metadata:
      labels:
        elastictype: kibana
        deployment: prod
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
            cpu: 1
  config:
    server.publicBaseUrl: https://kibana.k8s.wafflelab.online
    xpack.reporting.kibanaServer.hostname: kibana.k8s.wafflelab.online

