---
#test
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-wln
  namespace: default
spec:
  version: 9.3.1
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: elasticsearch-wln
          namespace: default
    logs:
      elasticsearchRefs:
        - name: elasticsearch-wln
          namespace: default
  nodeSets:
  - name: default
    config:
      node.roles: [ "master", "data", "ingest", "transform", "ml", "remote_cluster_client" ]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          deployment: prod
      spec:
        initContainers:
          - name: install-plugins
            command:
              ["sh", "-c", "bin/elasticsearch-plugin install mapper-size"]
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 2
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g"
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: local-data
  http:
    service:
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.8.80
    tls:
      #selfSignedCertificate:
      #  disabled: true
      certificate:
        secretName: elasticsearch-es-secret

