---

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 9.1.5
  nodeSets:
  - name: default
    config:
      node.roles: [ "master", "data", "ingest", "transform", "ml" ]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          deployment: prod
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms3g -Xmx3g"
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: local-data

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-es
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-es-http
            port:
              number: 9200
  tls:
  - hosts:
    - elasticsearch.k8s.wafflelab.online
    - elasticsearch.wafflab.net
    - elasticsearch.k8s.wafflab.net
    - elasticsearch-es-http
    - elasticsearch-es-http.default.svc
    - elasticsearch-es-http.default.svc.cluster.local
    secretName: elasticsearch-es-cert
