---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 9.3.3
  count: 1
  elasticsearchRef:
    name: elasticsearch-wln
  secureSettings:
  - secretName: kibana-kb-settings
  podTemplate:
    metadata:
      labels:
        elastictype: kibana
        deployment: prod
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
            cpu: 1
  config:
    server.publicBaseUrl: https://kibana.hids.one
    xpack.reporting.kibanaServer.hostname: kibana.hids.one
    xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch.hids.one"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet.hids.one"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: kubernetes
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_managed: true
        is_default_fleet_server: true
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
