---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 9.3.3
  count: 1
  elasticsearchRef:
    name: elasticsearch-wln
  secureSettings:
  - secretName: kibana-kb-settings
  podTemplate:
    metadata:
      labels:
        elastictype: kibana
        deployment: prod
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
            cpu: 1
  config:
    server.publicBaseUrl: https://kibana.hids.one
    xpack.reporting.kibanaServer.hostname: kibana.hids.one
    #xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch.hids.one"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet.hids.one"]
    #xpack.fleet.agents.elasticsearch.ca_sha256: "c2hhMjU2IEZpbmdlcnByaW50PUVEOjJEOjQ4OjREOjVFOjlEOjIyOjMwOjg4OkZEOjZCOjVGOjVGOjgyOjI4OkUyOkYwOjk5OjFBOjBBOjEyOjAxOkZBOkE4OkFFOjIyOjY2OjE2OjA1OjE1OjFGOjQ5Cg=="
    xpack.fleet.outputs:
      - id: fleet-default-output
        name: Default
        type: elasticsearch
        hosts: ["https://elasticsearch.hids.one"]
        #ssl:
        #  certificate_authorities: ["/mnt/additional-certs/ca.crt/ca.crt"]
        #ca_trusted_fingerprint: ED2D484D5E9D223088FD6B5F5F8228E2F0991A0A1201FAA8AE22661605151F49
        is_default: true
        is_default_monitoring: true
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: kubernetes
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_managed: true
        is_default_fleet_server: true
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Agent on ECK
        id: eck-agent
        is_managed: true
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-2
            id: system-2
            package:
              name: system
          - name: kubernetes
            id: kubernetes-2
            package:
              name: kubernetes
      - name: synthetics agent
        id: eck-synthetics-agent
        is_managed: true
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-2
            id: system-2
            package:
              name: system
