---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 9.3.3
  count: 1
  elasticsearchRef:
    name: elasticsearch-wln
  secureSettings:
  - secretName: kibana-kb-settings
  http:
    service:
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.8.81
    tls:
      selfSignedCertificate:
        disabled: true
      certificate:
        secretName: kibana-kb-secret
  podTemplate:
    metadata:
      labels:
        elastictype: kibana
        deployment: prod
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
            cpu: 1
  config:
    server.publicBaseUrl: https://kibana.k8s.wafflelab.online
    xpack.reporting.kibanaServer.hostname: kibana.k8s.wafflelab.online
    xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch.k8s.wafflelab.online:9200"]
    #xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch.k8s.wafflelab.online:9200", "https://elasticsearch-wln.default.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet.k8s.wafflelab.online:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: kubernetes
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_managed: true
        is_default_fleet_server: true
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: default
        is_managed: false
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
          - name: kubernetes-1
            id: kubernetes-1
            package:
              name: kubernetes
      - name: synthetics agent policy
        id: synth-agent
        namespace: default
        is_managed: false
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
      - name: synthetics agent policy
        id: synth-agent
        namespace: default
        is_managed: false
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
