---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-wln-service
  namespace: default
specc:
  type: LoadBalancer
  loadBalancertIP: 192.168.8.80
  ports:
  - port: 9200
  targetPort: 443
  selector:
    app: elasticsearch-ingress
