---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
spec:
  addresses:
  #- 192.168.10.0/24
  - 192.168.8.70-192.168.8.90

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lab
spec:
  ipAddressPools:
  - default-pool

