---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-elasticsearch2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.8.6:3260
    iqn: iqn.2018-07.online.wafflelab.k8s:elasticsearch2
    lun: 0
    fsType: ext4
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-elasticsearch1
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.8.6:3260
    iqn: iqn.2018-07.online.wafflelab.k8s:elasticsearch1
    lun: 0
    fsType: ext4
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-elasticsearch0
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.8.6:3260
    iqn: iqn.2018-07.online.wafflelab.k8s:elasticsearch0
    lun: 0
    fsType: ext4
    readOnly: false

