---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: hids-one-issuer
spec:
  acme:
    email: EMAIL_ADDRESS
    profile: tlsserver
    server: https://acme-staging-v02.api.letsencrypt.org/directory
  privateKeySecretRef:
    name: letsencrypt-staging
  solvers:
  - dns01:
      cloudflare:
        apiTokenSecretRef:
          name: cloudflare-api-token-secret
          key: api-token
