---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-hids-one
  namespace: default
spec:
  secretName: elasticsearch-es-secret
  isCA: false
  commonName: kibana.hids.one
  subject:
    organizations:
      - elastic
    organizationalUnits:
      - hids.one
  dnsNames:
    - kibana.hids.one
  issuerRef:
    kind: ClusterIssuer
    name: hids-one-issuer
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 8760h
  renewBefore: 7200h
